services:
  - type: web
    name: jobmatch-kelvin
    runtime: python
    buildCommand: apt-get install -y chromium-browser && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false